name: Data Processing Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenSSL
      run: sudo apt-get install openssl

    - name: Get x509 certificate
      run: |
        echo | openssl s_client -servername www.fibercop.it -connect www.fibercop.it:443 2>/dev/null | openssl x509 > fibercop.crt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Update Pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run data processing script
      env:
        SSL_CERT_FILE: ${{ github.workspace }}/fibercop.crt
      run: python data_processing.py
        
    - name: Remove temp files
      run: |- 
        rm ${{ github.workspace }}/fibercop.crt
        rm -rf ${{ github.workspace }}/tmp

    - name: Commit and push if data is changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
